[build]
  command = "npm run build"
  publish = "dist/public"
  functions = "dist/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"

[dev]
  framework = "vite"
  targetPort = 5173